// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_update_canary_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::update_canary::UpdateCanaryInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.artifact_config {
        #[allow(unused_mut)]
        let mut object_2 = object.key("ArtifactConfig").start_object();
        crate::protocol_serde::shape_artifact_config_input::ser_artifact_config_input(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.artifact_s3_location {
        object.key("ArtifactS3Location").string(var_3.as_str());
    }
    if let Some(var_4) = &input.code {
        #[allow(unused_mut)]
        let mut object_5 = object.key("Code").start_object();
        crate::protocol_serde::shape_canary_code_input::ser_canary_code_input(&mut object_5, var_4)?;
        object_5.finish();
    }
    if let Some(var_6) = &input.dry_run_id {
        object.key("DryRunId").string(var_6.as_str());
    }
    if let Some(var_7) = &input.execution_role_arn {
        object.key("ExecutionRoleArn").string(var_7.as_str());
    }
    if let Some(var_8) = &input.failure_retention_period_in_days {
        object.key("FailureRetentionPeriodInDays").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_8).into()),
        );
    }
    if let Some(var_9) = &input.provisioned_resource_cleanup {
        object.key("ProvisionedResourceCleanup").string(var_9.as_str());
    }
    if let Some(var_10) = &input.run_config {
        #[allow(unused_mut)]
        let mut object_11 = object.key("RunConfig").start_object();
        crate::protocol_serde::shape_canary_run_config_input::ser_canary_run_config_input(&mut object_11, var_10)?;
        object_11.finish();
    }
    if let Some(var_12) = &input.runtime_version {
        object.key("RuntimeVersion").string(var_12.as_str());
    }
    if let Some(var_13) = &input.schedule {
        #[allow(unused_mut)]
        let mut object_14 = object.key("Schedule").start_object();
        crate::protocol_serde::shape_canary_schedule_input::ser_canary_schedule_input(&mut object_14, var_13)?;
        object_14.finish();
    }
    if let Some(var_15) = &input.success_retention_period_in_days {
        object.key("SuccessRetentionPeriodInDays").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_15).into()),
        );
    }
    if let Some(var_16) = &input.visual_reference {
        #[allow(unused_mut)]
        let mut object_17 = object.key("VisualReference").start_object();
        crate::protocol_serde::shape_visual_reference_input::ser_visual_reference_input(&mut object_17, var_16)?;
        object_17.finish();
    }
    if let Some(var_18) = &input.vpc_config {
        #[allow(unused_mut)]
        let mut object_19 = object.key("VpcConfig").start_object();
        crate::protocol_serde::shape_vpc_config_input::ser_vpc_config_input(&mut object_19, var_18)?;
        object_19.finish();
    }
    Ok(())
}
