[package]
name = "transcribestreaming"
version = "0.1.0"
authors = ["John DiSanti <jdisanti@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../aws-config" }
aws-sdk-transcribestreaming = { package = "aws-sdk-transcribestreaming", path = "../../transcribestreaming" }
aws-types = { path = "../../aws-types" }

async-stream = "0.3"
bytes = "1"
hound = "3.4"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2.18"
