// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_srt_listener_decryption_request(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::SrtListenerDecryptionRequest,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.algorithm {
        object.key("algorithm").string(var_1.as_str());
    }
    if let Some(var_2) = &input.passphrase_secret_arn {
        object.key("passphraseSecretArn").string(var_2.as_str());
    }
    Ok(())
}
