// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p> The <code>ListJobsByStatusResponse</code> structure. </p>
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct ListJobsByStatusOutput  {
    /// <p>An array of <code>Job</code> objects that have the specified status.</p>
    #[doc(hidden)]
    pub jobs: std::option::Option<std::vec::Vec<crate::types::Job>>,
    /// <p> A value that you use to access the second and subsequent pages of results, if any. When the jobs in the specified pipeline fit on one page or when you've reached the last page of results, the value of <code>NextPageToken</code> is <code>null</code>. </p>
    #[doc(hidden)]
    pub next_page_token: std::option::Option<std::string::String>,
    _request_id: Option<String>,
}
impl ListJobsByStatusOutput {
    /// <p>An array of <code>Job</code> objects that have the specified status.</p>
    pub fn jobs(&self) -> std::option::Option<& [crate::types::Job]> {
        self.jobs.as_deref()
    }
    /// <p> A value that you use to access the second and subsequent pages of results, if any. When the jobs in the specified pipeline fit on one page or when you've reached the last page of results, the value of <code>NextPageToken</code> is <code>null</code>. </p>
    pub fn next_page_token(&self) -> std::option::Option<& str> {
        self.next_page_token.as_deref()
    }
}
impl aws_http::request_id::RequestId for ListJobsByStatusOutput {
                                fn request_id(&self) -> Option<&str> {
                                    self._request_id.as_deref()
                                }
                            }
impl ListJobsByStatusOutput {
    /// Creates a new builder-style object to manufacture [`ListJobsByStatusOutput`](crate::operation::list_jobs_by_status::ListJobsByStatusOutput).
    pub fn builder() -> crate::operation::list_jobs_by_status::builders::ListJobsByStatusOutputBuilder {
        crate::operation::list_jobs_by_status::builders::ListJobsByStatusOutputBuilder::default()
    }
}

/// A builder for [`ListJobsByStatusOutput`](crate::operation::list_jobs_by_status::ListJobsByStatusOutput).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default, std::fmt::Debug)]
pub struct ListJobsByStatusOutputBuilder {
    pub(crate) jobs: std::option::Option<std::vec::Vec<crate::types::Job>>,
    pub(crate) next_page_token: std::option::Option<std::string::String>,
    _request_id: Option<String>,
}
impl ListJobsByStatusOutputBuilder {
    /// Appends an item to `jobs`.
    ///
    /// To override the contents of this collection use [`set_jobs`](Self::set_jobs).
    ///
    /// <p>An array of <code>Job</code> objects that have the specified status.</p>
    pub fn jobs(mut self, input: crate::types::Job) -> Self {
        let mut v = self.jobs.unwrap_or_default();
                        v.push(input);
                        self.jobs = Some(v);
                        self
    }
    /// <p>An array of <code>Job</code> objects that have the specified status.</p>
    pub fn set_jobs(mut self, input: std::option::Option<std::vec::Vec<crate::types::Job>>) -> Self {
        self.jobs = input; self
    }
    /// <p> A value that you use to access the second and subsequent pages of results, if any. When the jobs in the specified pipeline fit on one page or when you've reached the last page of results, the value of <code>NextPageToken</code> is <code>null</code>. </p>
    pub fn next_page_token(mut self, input: impl Into<std::string::String>) -> Self {
        self.next_page_token = Some(input.into());
        self
    }
    /// <p> A value that you use to access the second and subsequent pages of results, if any. When the jobs in the specified pipeline fit on one page or when you've reached the last page of results, the value of <code>NextPageToken</code> is <code>null</code>. </p>
    pub fn set_next_page_token(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.next_page_token = input; self
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
                                    self._request_id = Some(request_id.into());
                                    self
                                }
    
                                pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
                                    self._request_id = request_id;
                                    self
                                }
    /// Consumes the builder and constructs a [`ListJobsByStatusOutput`](crate::operation::list_jobs_by_status::ListJobsByStatusOutput).
    pub fn build(self) -> crate::operation::list_jobs_by_status::ListJobsByStatusOutput {
        crate::operation::list_jobs_by_status::ListJobsByStatusOutput {
            jobs: self.jobs
            ,
            next_page_token: self.next_page_token
            ,
            _request_id: self._request_id,
        }
    }
}

