// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct UnfilteredPartition  {
    /// <p>Represents a slice of table data.</p>
    #[doc(hidden)]
    pub partition: std::option::Option<crate::types::Partition>,
    #[allow(missing_docs)] // documentation missing in model
    #[doc(hidden)]
    pub authorized_columns: std::option::Option<std::vec::Vec<std::string::String>>,
    #[allow(missing_docs)] // documentation missing in model
    #[doc(hidden)]
    pub is_registered_with_lake_formation: bool,
}
impl UnfilteredPartition {
    /// <p>Represents a slice of table data.</p>
    pub fn partition(&self) -> std::option::Option<& crate::types::Partition> {
        self.partition.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn authorized_columns(&self) -> std::option::Option<& [std::string::String]> {
        self.authorized_columns.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn is_registered_with_lake_formation(&self) -> bool {
        self.is_registered_with_lake_formation
    }
}
impl UnfilteredPartition {
    /// Creates a new builder-style object to manufacture [`UnfilteredPartition`](crate::types::UnfilteredPartition).
    pub fn builder() -> crate::types::builders::UnfilteredPartitionBuilder {
        crate::types::builders::UnfilteredPartitionBuilder::default()
    }
}

/// A builder for [`UnfilteredPartition`](crate::types::UnfilteredPartition).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default, std::fmt::Debug)]
pub struct UnfilteredPartitionBuilder {
    pub(crate) partition: std::option::Option<crate::types::Partition>,
    pub(crate) authorized_columns: std::option::Option<std::vec::Vec<std::string::String>>,
    pub(crate) is_registered_with_lake_formation: std::option::Option<bool>,
}
impl UnfilteredPartitionBuilder {
    /// <p>Represents a slice of table data.</p>
    pub fn partition(mut self, input: crate::types::Partition) -> Self {
        self.partition = Some(input);
        self
    }
    /// <p>Represents a slice of table data.</p>
    pub fn set_partition(mut self, input: std::option::Option<crate::types::Partition>) -> Self {
        self.partition = input; self
    }
    /// Appends an item to `authorized_columns`.
    ///
    /// To override the contents of this collection use [`set_authorized_columns`](Self::set_authorized_columns).
    ///
    pub fn authorized_columns(mut self, input: impl Into<std::string::String>) -> Self {
        let mut v = self.authorized_columns.unwrap_or_default();
                        v.push(input.into());
                        self.authorized_columns = Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_authorized_columns(mut self, input: std::option::Option<std::vec::Vec<std::string::String>>) -> Self {
        self.authorized_columns = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn is_registered_with_lake_formation(mut self, input: bool) -> Self {
        self.is_registered_with_lake_formation = Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_is_registered_with_lake_formation(mut self, input: std::option::Option<bool>) -> Self {
        self.is_registered_with_lake_formation = input; self
    }
    /// Consumes the builder and constructs a [`UnfilteredPartition`](crate::types::UnfilteredPartition).
    pub fn build(self) -> crate::types::UnfilteredPartition {
        crate::types::UnfilteredPartition {
            partition: self.partition
            ,
            authorized_columns: self.authorized_columns
            ,
            is_registered_with_lake_formation: self.is_registered_with_lake_formation
                .unwrap_or_default()
            ,
        }
    }
}

