// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetChallengePasswordInput {
    /// <p>The Amazon Resource Name (ARN) of the challenge.</p>
    pub challenge_arn: ::std::option::Option<::std::string::String>,
}
impl GetChallengePasswordInput {
    /// <p>The Amazon Resource Name (ARN) of the challenge.</p>
    pub fn challenge_arn(&self) -> ::std::option::Option<&str> {
        self.challenge_arn.as_deref()
    }
}
impl GetChallengePasswordInput {
    /// Creates a new builder-style object to manufacture [`GetChallengePasswordInput`](crate::operation::get_challenge_password::GetChallengePasswordInput).
    pub fn builder() -> crate::operation::get_challenge_password::builders::GetChallengePasswordInputBuilder {
        crate::operation::get_challenge_password::builders::GetChallengePasswordInputBuilder::default()
    }
}

/// A builder for [`GetChallengePasswordInput`](crate::operation::get_challenge_password::GetChallengePasswordInput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct GetChallengePasswordInputBuilder {
    pub(crate) challenge_arn: ::std::option::Option<::std::string::String>,
}
impl GetChallengePasswordInputBuilder {
    /// <p>The Amazon Resource Name (ARN) of the challenge.</p>
    /// This field is required.
    pub fn challenge_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.challenge_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the challenge.</p>
    pub fn set_challenge_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.challenge_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the challenge.</p>
    pub fn get_challenge_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.challenge_arn
    }
    /// Consumes the builder and constructs a [`GetChallengePasswordInput`](crate::operation::get_challenge_password::GetChallengePasswordInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::get_challenge_password::GetChallengePasswordInput, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::operation::get_challenge_password::GetChallengePasswordInput {
            challenge_arn: self.challenge_arn,
        })
    }
}
