// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct DeleteNotificationRuleInput  {
    /// <p>The Amazon Resource Name (ARN) of the notification rule you want to delete.</p>
    #[doc(hidden)]
    pub arn: std::option::Option<std::string::String>,
}
impl DeleteNotificationRuleInput {
    /// <p>The Amazon Resource Name (ARN) of the notification rule you want to delete.</p>
    pub fn arn(&self) -> std::option::Option<& str> {
        self.arn.as_deref()
    }
}
impl DeleteNotificationRuleInput {
    /// Creates a new builder-style object to manufacture [`DeleteNotificationRuleInput`](crate::operation::delete_notification_rule::DeleteNotificationRuleInput).
    pub fn builder() -> crate::operation::delete_notification_rule::builders::DeleteNotificationRuleInputBuilder {
        crate::operation::delete_notification_rule::builders::DeleteNotificationRuleInputBuilder::default()
    }
}

/// A builder for [`DeleteNotificationRuleInput`](crate::operation::delete_notification_rule::DeleteNotificationRuleInput).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default, std::fmt::Debug)]
pub struct DeleteNotificationRuleInputBuilder {
    pub(crate) arn: std::option::Option<std::string::String>,
}
impl DeleteNotificationRuleInputBuilder {
    /// <p>The Amazon Resource Name (ARN) of the notification rule you want to delete.</p>
    pub fn arn(mut self, input: impl Into<std::string::String>) -> Self {
        self.arn = Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the notification rule you want to delete.</p>
    pub fn set_arn(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.arn = input; self
    }
    /// Consumes the builder and constructs a [`DeleteNotificationRuleInput`](crate::operation::delete_notification_rule::DeleteNotificationRuleInput).
    pub fn build(self) -> Result<crate::operation::delete_notification_rule::DeleteNotificationRuleInput, aws_smithy_http::operation::error::BuildError> {
        Ok(
            crate::operation::delete_notification_rule::DeleteNotificationRuleInput {
                arn: self.arn
                ,
            }
        )
    }
}

