// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The attributes of a skill group.</p>
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct SkillGroupData  {
    /// <p>The skill group ARN of a skill group.</p>
    #[doc(hidden)]
    pub skill_group_arn: std::option::Option<std::string::String>,
    /// <p>The skill group name of a skill group.</p>
    #[doc(hidden)]
    pub skill_group_name: std::option::Option<std::string::String>,
    /// <p>The description of a skill group.</p>
    #[doc(hidden)]
    pub description: std::option::Option<std::string::String>,
}
impl SkillGroupData {
    /// <p>The skill group ARN of a skill group.</p>
    pub fn skill_group_arn(&self) -> std::option::Option<& str> {
        self.skill_group_arn.as_deref()
    }
    /// <p>The skill group name of a skill group.</p>
    pub fn skill_group_name(&self) -> std::option::Option<& str> {
        self.skill_group_name.as_deref()
    }
    /// <p>The description of a skill group.</p>
    pub fn description(&self) -> std::option::Option<& str> {
        self.description.as_deref()
    }
}
impl SkillGroupData {
    /// Creates a new builder-style object to manufacture [`SkillGroupData`](crate::types::SkillGroupData).
    pub fn builder() -> crate::types::builders::SkillGroupDataBuilder {
        crate::types::builders::SkillGroupDataBuilder::default()
    }
}

/// A builder for [`SkillGroupData`](crate::types::SkillGroupData).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default, std::fmt::Debug)]
pub struct SkillGroupDataBuilder {
    pub(crate) skill_group_arn: std::option::Option<std::string::String>,
    pub(crate) skill_group_name: std::option::Option<std::string::String>,
    pub(crate) description: std::option::Option<std::string::String>,
}
impl SkillGroupDataBuilder {
    /// <p>The skill group ARN of a skill group.</p>
    pub fn skill_group_arn(mut self, input: impl Into<std::string::String>) -> Self {
        self.skill_group_arn = Some(input.into());
        self
    }
    /// <p>The skill group ARN of a skill group.</p>
    pub fn set_skill_group_arn(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.skill_group_arn = input; self
    }
    /// <p>The skill group name of a skill group.</p>
    pub fn skill_group_name(mut self, input: impl Into<std::string::String>) -> Self {
        self.skill_group_name = Some(input.into());
        self
    }
    /// <p>The skill group name of a skill group.</p>
    pub fn set_skill_group_name(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.skill_group_name = input; self
    }
    /// <p>The description of a skill group.</p>
    pub fn description(mut self, input: impl Into<std::string::String>) -> Self {
        self.description = Some(input.into());
        self
    }
    /// <p>The description of a skill group.</p>
    pub fn set_description(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.description = input; self
    }
    /// Consumes the builder and constructs a [`SkillGroupData`](crate::types::SkillGroupData).
    pub fn build(self) -> crate::types::SkillGroupData {
        crate::types::SkillGroupData {
            skill_group_arn: self.skill_group_arn
            ,
            skill_group_name: self.skill_group_name
            ,
            description: self.description
            ,
        }
    }
}

