[package]
name = "sqs-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqs = { package = "aws-sdk-sqs", path = "../../sqs" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2.18"