// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p> Describes the request structure for the delete app request. </p>
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct DeleteAppInput  {
    /// <p> The unique ID for an Amplify app. </p>
    #[doc(hidden)]
    pub app_id: std::option::Option<std::string::String>,
}
impl DeleteAppInput {
    /// <p> The unique ID for an Amplify app. </p>
    pub fn app_id(&self) -> std::option::Option<& str> {
        self.app_id.as_deref()
    }
}
impl DeleteAppInput {
    /// Creates a new builder-style object to manufacture [`DeleteAppInput`](crate::operation::delete_app::DeleteAppInput).
    pub fn builder() -> crate::operation::delete_app::builders::DeleteAppInputBuilder {
        crate::operation::delete_app::builders::DeleteAppInputBuilder::default()
    }
}

/// A builder for [`DeleteAppInput`](crate::operation::delete_app::DeleteAppInput).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default, std::fmt::Debug)]
pub struct DeleteAppInputBuilder {
    pub(crate) app_id: std::option::Option<std::string::String>,
}
impl DeleteAppInputBuilder {
    /// <p> The unique ID for an Amplify app. </p>
    pub fn app_id(mut self, input: impl Into<std::string::String>) -> Self {
        self.app_id = Some(input.into());
        self
    }
    /// <p> The unique ID for an Amplify app. </p>
    pub fn set_app_id(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.app_id = input; self
    }
    /// Consumes the builder and constructs a [`DeleteAppInput`](crate::operation::delete_app::DeleteAppInput).
    pub fn build(self) -> Result<crate::operation::delete_app::DeleteAppInput, aws_smithy_http::operation::error::BuildError> {
        Ok(
            crate::operation::delete_app::DeleteAppInput {
                app_id: self.app_id
                ,
            }
        )
    }
}

