[package]
name = "canary-runner"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Tool used to run the canary tests in CI"
edition = "2018"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
anyhow = "1"
aws-config = "0.3"
aws-sdk-lambda = "0.3"
aws-sdk-s3 = "0.3"
base64 = "0.13"
crates_io_api = "0.7"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }