// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_delete_solution_input(object: &mut aws_smithy_json::serialize::JsonObjectWriter, input: &crate::operation::delete_solution::DeleteSolutionInput) -> Result<(), aws_smithy_http::operation::error::SerializationError> {
    if let Some(var_1) = &input.solution_arn {
        object.key("solutionArn").string(var_1.as_str());
    }
    Ok(())
}

