#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script contains additional CI checks to run for this specific package

set -e

echo "### Checking for duplicate dependency versions in the normal dependency graph with all features enabled"
cargo tree -d --edges normal --all-features

FEATURES=(
    "hardcoded-credentials"
)
for feature in "${FEATURES[@]}"; do
    echo "### Checking feature '${feature}'..."
    cargo test --no-default-features --features "${feature}"
done
