// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// An exception thrown when a bulk publish operation is requested less than 24 hours after a previous bulk publish operation completed successfully.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AlreadyStreamedException {
    /// The message associated with the AlreadyStreamedException exception.
    pub message: ::std::string::String,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
impl AlreadyStreamedException {
    /// Returns the error message.
    pub fn message(&self) -> &str {
        &self.message
    }
}
impl ::std::fmt::Display for AlreadyStreamedException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "AlreadyStreamedException")?;
        {
            ::std::write!(f, ": {}", &self.message)?;
        }
        Ok(())
    }
}
impl ::std::error::Error for AlreadyStreamedException {}
impl ::aws_types::request_id::RequestId for crate::types::error::AlreadyStreamedException {
    fn request_id(&self) -> Option<&str> {
        use ::aws_smithy_types::error::metadata::ProvideErrorMetadata;
        self.meta().request_id()
    }
}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for AlreadyStreamedException {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        &self.meta
    }
}
impl AlreadyStreamedException {
    /// Creates a new builder-style object to manufacture [`AlreadyStreamedException`](crate::types::error::AlreadyStreamedException).
    pub fn builder() -> crate::types::error::builders::AlreadyStreamedExceptionBuilder {
        crate::types::error::builders::AlreadyStreamedExceptionBuilder::default()
    }
}

/// A builder for [`AlreadyStreamedException`](crate::types::error::AlreadyStreamedException).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct AlreadyStreamedExceptionBuilder {
    pub(crate) message: ::std::option::Option<::std::string::String>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl AlreadyStreamedExceptionBuilder {
    /// The message associated with the AlreadyStreamedException exception.
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    /// The message associated with the AlreadyStreamedException exception.
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    /// The message associated with the AlreadyStreamedException exception.
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Sets error metadata
    pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
        self.meta = Some(meta);
        self
    }

    /// Sets error metadata
    pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
        self.meta = meta;
        self
    }
    /// Consumes the builder and constructs a [`AlreadyStreamedException`](crate::types::error::AlreadyStreamedException).
    /// This method will fail if any of the following fields are not set:
    /// - [`message`](crate::types::error::builders::AlreadyStreamedExceptionBuilder::message)
    pub fn build(self) -> ::std::result::Result<crate::types::error::AlreadyStreamedException, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::error::AlreadyStreamedException {
            message: self.message.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "message",
                    "message was not specified but it is required when building AlreadyStreamedException",
                )
            })?,
            meta: self.meta.unwrap_or_default(),
        })
    }
}
