// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Disabled Locking Settings
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DisabledLockingSettings {
    /// Optional. Only applies to CMAF Ingest Output Group and MediaPackage V2 Output Group. Enter a value here to use a custom epoch, instead of the standard epoch (which started at 1970-01-01T00:00:00 UTC). Specify the start time of the custom epoch, in YYYY-MM-DDTHH:MM:SS in UTC. The time must be 2000-01-01T00:00:00 or later. Always set the MM:SS portion to 00:00.
    pub custom_epoch: ::std::option::Option<::std::string::String>,
}
impl DisabledLockingSettings {
    /// Optional. Only applies to CMAF Ingest Output Group and MediaPackage V2 Output Group. Enter a value here to use a custom epoch, instead of the standard epoch (which started at 1970-01-01T00:00:00 UTC). Specify the start time of the custom epoch, in YYYY-MM-DDTHH:MM:SS in UTC. The time must be 2000-01-01T00:00:00 or later. Always set the MM:SS portion to 00:00.
    pub fn custom_epoch(&self) -> ::std::option::Option<&str> {
        self.custom_epoch.as_deref()
    }
}
impl DisabledLockingSettings {
    /// Creates a new builder-style object to manufacture [`DisabledLockingSettings`](crate::types::DisabledLockingSettings).
    pub fn builder() -> crate::types::builders::DisabledLockingSettingsBuilder {
        crate::types::builders::DisabledLockingSettingsBuilder::default()
    }
}

/// A builder for [`DisabledLockingSettings`](crate::types::DisabledLockingSettings).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DisabledLockingSettingsBuilder {
    pub(crate) custom_epoch: ::std::option::Option<::std::string::String>,
}
impl DisabledLockingSettingsBuilder {
    /// Optional. Only applies to CMAF Ingest Output Group and MediaPackage V2 Output Group. Enter a value here to use a custom epoch, instead of the standard epoch (which started at 1970-01-01T00:00:00 UTC). Specify the start time of the custom epoch, in YYYY-MM-DDTHH:MM:SS in UTC. The time must be 2000-01-01T00:00:00 or later. Always set the MM:SS portion to 00:00.
    pub fn custom_epoch(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.custom_epoch = ::std::option::Option::Some(input.into());
        self
    }
    /// Optional. Only applies to CMAF Ingest Output Group and MediaPackage V2 Output Group. Enter a value here to use a custom epoch, instead of the standard epoch (which started at 1970-01-01T00:00:00 UTC). Specify the start time of the custom epoch, in YYYY-MM-DDTHH:MM:SS in UTC. The time must be 2000-01-01T00:00:00 or later. Always set the MM:SS portion to 00:00.
    pub fn set_custom_epoch(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.custom_epoch = input;
        self
    }
    /// Optional. Only applies to CMAF Ingest Output Group and MediaPackage V2 Output Group. Enter a value here to use a custom epoch, instead of the standard epoch (which started at 1970-01-01T00:00:00 UTC). Specify the start time of the custom epoch, in YYYY-MM-DDTHH:MM:SS in UTC. The time must be 2000-01-01T00:00:00 or later. Always set the MM:SS portion to 00:00.
    pub fn get_custom_epoch(&self) -> &::std::option::Option<::std::string::String> {
        &self.custom_epoch
    }
    /// Consumes the builder and constructs a [`DisabledLockingSettings`](crate::types::DisabledLockingSettings).
    pub fn build(self) -> crate::types::DisabledLockingSettings {
        crate::types::DisabledLockingSettings {
            custom_epoch: self.custom_epoch,
        }
    }
}
