[package]
name = "aws-auth"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithy-http = { path = "../smithy-http" }
zeroize = "1.2.0"

[dev-dependencies]
http = "0.2.3"
tokio = { version = "1.0", features = ["rt", "macros"] }
async-trait = "0.1.50"
