[package]
name = "aws-auth"
version = "0.0.21-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "AWS auth middleware."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
rt-tokio = ["smithy-async/rt-tokio"]
default = ["rt-tokio"]

[dependencies]
pin-project = "1"
smithy-async = { path = "../smithy-async", default-features = false }
smithy-http = { path = "../smithy-http" }
aws-types = { path = "../aws-types" }
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
zeroize = "1.2.0"

[dev-dependencies]
async-trait = "0.1.50"
env_logger = "*"
http = "0.2.3"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "test-util"] }
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
smithy-async = { path = "../smithy-async", features = ["rt-tokio"] }