[package]
name = "aws-smithy-json"
version = "0.30.0-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
description = "Token streaming JSON parser for smithy-rs."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-types = { path = "../aws-smithy-types" }

[dev-dependencies]
proptest = "1"
serde_json = "1.0"