[package]
name = "protocol-test-helpers"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = "A collection of library functions to validate HTTP requests against Smithy protocol tests"
license = "Apache-2.0"

[dependencies]
http = "0.2.1"
thiserror = "1"
serde_json = "1"
regex = "1.5"
# Not perfect for our needs, but good for now
assert-json-diff = "1"

pretty_assertions = "0.7.2"
roxmltree = "0.14.1"
