// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CreateMonitor`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`client_token(impl Into<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::client_token) / [`set_client_token(Option<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::set_client_token):<br>required: **false**<br><p>The unique token which the server uses to recognize retries of the same request.</p><br>
    ///   - [`display_name(impl Into<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::display_name) / [`set_display_name(Option<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::set_display_name):<br>required: **true**<br><p>The name that you give the monitor that is displayed in the Deadline Cloud console.</p><br>
    ///   - [`identity_center_instance_arn(impl Into<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::identity_center_instance_arn) / [`set_identity_center_instance_arn(Option<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::set_identity_center_instance_arn):<br>required: **true**<br><p>The Amazon Resource Name (ARN) of the IAM Identity Center instance that authenticates monitor users.</p><br>
    ///   - [`subdomain(impl Into<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::subdomain) / [`set_subdomain(Option<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::set_subdomain):<br>required: **true**<br><p>The subdomain to use when creating the monitor URL. The full URL of the monitor is subdomain.Region.deadlinecloud.amazonaws.com.</p><br>
    ///   - [`role_arn(impl Into<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::role_arn) / [`set_role_arn(Option<String>)`](crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::set_role_arn):<br>required: **true**<br><p>The Amazon Resource Name (ARN) of the IAM role that the monitor uses to connect to Deadline Cloud. Every user that signs in to the monitor using IAM Identity Center uses this role to access Deadline Cloud resources.</p><br>
    /// - On success, responds with [`CreateMonitorOutput`](crate::operation::create_monitor::CreateMonitorOutput) with field(s):
    ///   - [`monitor_id(String)`](crate::operation::create_monitor::CreateMonitorOutput::monitor_id): <p>The unique identifier of the monitor.</p>
    ///   - [`identity_center_application_arn(String)`](crate::operation::create_monitor::CreateMonitorOutput::identity_center_application_arn): <p>The Amazon Resource Name (ARN) that IAM Identity Center assigns to the monitor.</p>
    /// - On failure, responds with [`SdkError<CreateMonitorError>`](crate::operation::create_monitor::CreateMonitorError)
    pub fn create_monitor(&self) -> crate::operation::create_monitor::builders::CreateMonitorFluentBuilder {
        crate::operation::create_monitor::builders::CreateMonitorFluentBuilder::new(self.handle.clone())
    }
}
