[package]
name = "smithy-http"
edition = "2018"
version = "0.26.0-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Smithy HTTP logic for smithy-rs."
keywords = []
categories = []
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
autobins = true
autoexamples = true
autotests = true
autobenches = true
publish = true
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bytes = "1"
bytes-utils = "0.1"
futures-core = "0.3.14"
http = "0.2.3"
http-body = "0.4.0"
hyper = "0.14.5"
percent-encoding = "2.1.0"
pin-project = "1"
thiserror = "1"
tracing = "0.1"

[dependencies.smithy-eventstream]
version = "0.26.0-alpha"
path = "../smithy-eventstream"
features = []
optional = true

[dependencies.smithy-types]
version = "0.26.0-alpha"
path = "../smithy-types"
features = []
optional = false

[dependencies.tokio]
version = "1.6"
features = []
optional = true

[dependencies.tokio-util]
version = "0.6"
features = []
optional = true

[dev-dependencies]
async-stream = "0.3"
futures-util = "0.3"
proptest = "1"
tempfile = "3.2.0"
tokio-stream = "0.1.5"

[dev-dependencies.hyper]
version = "0.14.5"
features = ["stream"]
optional = false

[dev-dependencies.tokio]
version = "1.6"
features = ["macros", "rt", "rt-multi-thread", "fs", "io-util"]
optional = false

[features]
bytestream-util = ["tokio/fs", "tokio-util/io"]
default = ["bytestream-util"]
event-stream = ["smithy-eventstream"]
