[package]
name = "smithy-http"
version = "0.0.1"
authors = ["rcoh@amazon.com"]
edition = "2018"
license = "Apache-2.0"

[features]
bytestream-util = ["tokio/fs", "tokio-util/io"]
event-stream = ["smithy-eventstream"]
default = ["bytestream-util"]

[dependencies]
smithy-types = { path = "../smithy-types" }
smithy-eventstream = { path = "../smithy-eventstream", optional = true }
bytes = "1"
bytes-utils = "0.1"
http-body = "0.4.0"
http = "0.2.3"
thiserror = "1"
pin-project = "1"
percent-encoding = "2.1.0"
tracing = "0.1"

# We are using hyper for our streaming body implementation, but this is an internal detail.
hyper = "0.14.5"

# ByteStream internals
futures-core = "0.3.14"
tokio = { version = "1.6", optional = true }
tokio-util = { version = "0.6", optional = true}

[dev-dependencies]
async-stream = "0.3"
futures-util = "0.3"
hyper = { version = "0.14.5", features = ["stream"] }
proptest = "1"
tokio = {version = "1.6", features = ["macros", "rt", "fs", "io-util"]}
tokio-stream = "0.1.5"
tempfile = "3.2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
