name: "\U0001F680 Feature request"
description: Suggest an idea for this project
title: "[request]: Describe request here"
labels: [feature-request, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        <!-- Please keep this note for the community -->
        ### Community Note
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue, please leave a comment
        <!-- Thank you for keeping this note for the community -->

  - type: textarea
    id: description
    attributes:
      label: Tell us about your request
      description: What do you want us to build?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Tell us about the problem you're trying to solve.
      description: |
        What are you trying to do, and why is it hard? What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Are you currently working around this issue?
      description: |
        How are you currently solving this problem?
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: |
        Anything else we should know?
    validations:
      required: false
