name: General Issue
description: Create a new issue
title: "short issue description"
labels: [needs-triage, guidance]
body:
  - type: checkboxes
    id: issues
    attributes:
      label:
      description:
      options:
        - label: I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
          required: true
        - label: I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.
          required: true
          
  - type: checkboxes
    id: guide
    attributes:
      label:
      description:
      options:
        - label: I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.
          required: true
          
  - type: input
    id: issue
    attributes:
      label: General Issue
      description: |
        Describe the question
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question Description
      description: |
        Ask your question here. Include any details relevant. Make sure you are not falling prey to the [X/Y problem](http://xyproblem.info)!
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Platform/OS/Device
    validations:
      required: false

  - type: input
    id: language-version
    attributes:
      label: Language Version
      description: E.g. Rust 1.57.0
    validations:
      required: false

