// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client  {
    /// Constructs a fluent builder for the [`DeactivateMFADevice`](crate::client::fluent_builders::DeactivateMFADevice) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`user_name(impl Into<String>)`](crate::client::fluent_builders::DeactivateMFADevice::user_name) / [`set_user_name(Option<String>)`](crate::client::fluent_builders::DeactivateMFADevice::set_user_name): <p>The name of the user whose MFA device you want to deactivate.</p>  <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>
    ///   - [`serial_number(impl Into<String>)`](crate::client::fluent_builders::DeactivateMFADevice::serial_number) / [`set_serial_number(Option<String>)`](crate::client::fluent_builders::DeactivateMFADevice::set_serial_number): <p>The serial number that uniquely identifies the MFA device. For virtual MFA devices, the serial number is the device ARN.</p>  <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: =,.@:/-</p>
                            /// - On success, responds with [`DeactivateMfaDeviceOutput`](crate::output::DeactivateMfaDeviceOutput)
                            /// - On failure, responds with [`SdkError<DeactivateMFADeviceError>`](crate::error::DeactivateMFADeviceError)
    pub fn deactivate_mfa_device(&self) -> crate::client::fluent_builders::DeactivateMFADevice {
                                crate::client::fluent_builders::DeactivateMFADevice::new(self.handle.clone())
                            }
}

