// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When writing a match expression against `MigProfileType`, it is important to ensure
/// your code is forward-compatible. That is, if a match arm handles a case for a
/// feature that is supported by the service but has not been represented as an enum
/// variant in a current version of SDK, your code should continue to work when you
/// upgrade SDK to a future version in which the enum does include a variant for that
/// feature.
///
/// Here is an example of how you can make a match expression forward-compatible:
///
/// ```text
/// # let migprofiletype = unimplemented!();
/// match migprofiletype {
///     MigProfileType::Mig1G10Gb => { /* ... */ },
///     MigProfileType::Mig1G18Gb => { /* ... */ },
///     MigProfileType::Mig1G20Gb => { /* ... */ },
///     MigProfileType::Mig1G23Gb => { /* ... */ },
///     MigProfileType::Mig1G35Gb => { /* ... */ },
///     MigProfileType::Mig1G45Gb => { /* ... */ },
///     MigProfileType::Mig1G47Gb => { /* ... */ },
///     MigProfileType::Mig1G5Gb => { /* ... */ },
///     MigProfileType::Mig2G10Gb => { /* ... */ },
///     MigProfileType::Mig2G20Gb => { /* ... */ },
///     MigProfileType::Mig2G35Gb => { /* ... */ },
///     MigProfileType::Mig2G45Gb => { /* ... */ },
///     MigProfileType::Mig2G47Gb => { /* ... */ },
///     MigProfileType::Mig3G20Gb => { /* ... */ },
///     MigProfileType::Mig3G40Gb => { /* ... */ },
///     MigProfileType::Mig3G71Gb => { /* ... */ },
///     MigProfileType::Mig3G90Gb => { /* ... */ },
///     MigProfileType::Mig3G93Gb => { /* ... */ },
///     MigProfileType::Mig4G20Gb => { /* ... */ },
///     MigProfileType::Mig4G40Gb => { /* ... */ },
///     MigProfileType::Mig4G71Gb => { /* ... */ },
///     MigProfileType::Mig4G90Gb => { /* ... */ },
///     MigProfileType::Mig4G93Gb => { /* ... */ },
///     MigProfileType::Mig7G141Gb => { /* ... */ },
///     MigProfileType::Mig7G180Gb => { /* ... */ },
///     MigProfileType::Mig7G186Gb => { /* ... */ },
///     MigProfileType::Mig7G40Gb => { /* ... */ },
///     MigProfileType::Mig7G80Gb => { /* ... */ },
///     other @ _ if other.as_str() == "NewFeature" => { /* handles a case for `NewFeature` */ },
///     _ => { /* ... */ },
/// }
/// ```
/// The above code demonstrates that when `migprofiletype` represents
/// `NewFeature`, the execution path will lead to the second last match arm,
/// even though the enum does not contain a variant `MigProfileType::NewFeature`
/// in the current version of SDK. The reason is that the variable `other`,
/// created by the `@` operator, is bound to
/// `MigProfileType::Unknown(UnknownVariantValue("NewFeature".to_owned()))`
/// and calling `as_str` on it yields `"NewFeature"`.
/// This match expression is forward-compatible when executed with a newer
/// version of SDK where the variant `MigProfileType::NewFeature` is defined.
/// Specifically, when `migprofiletype` represents `NewFeature`,
/// the execution path will hit the second last match arm as before by virtue of
/// calling `as_str` on `MigProfileType::NewFeature` also yielding `"NewFeature"`.
///
/// Explicitly matching on the `Unknown` variant should
/// be avoided for two reasons:
/// - The inner data `UnknownVariantValue` is opaque, and no further information can be extracted.
/// - It might inadvertently shadow other intended match arms.
///
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::Ord, ::std::cmp::PartialEq, ::std::cmp::PartialOrd, ::std::fmt::Debug, ::std::hash::Hash,
)]
pub enum MigProfileType {
    #[allow(missing_docs)] // documentation missing in model
    Mig1G10Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G18Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G20Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G23Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G35Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G45Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G47Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig1G5Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig2G10Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig2G20Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig2G35Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig2G45Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig2G47Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig3G20Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig3G40Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig3G71Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig3G90Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig3G93Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig4G20Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig4G40Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig4G71Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig4G90Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig4G93Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig7G141Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig7G180Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig7G186Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig7G40Gb,
    #[allow(missing_docs)] // documentation missing in model
    Mig7G80Gb,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants.")]
    Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for MigProfileType {
    fn from(s: &str) -> Self {
        match s {
            "mig-1g.10gb" => MigProfileType::Mig1G10Gb,
            "mig-1g.18gb" => MigProfileType::Mig1G18Gb,
            "mig-1g.20gb" => MigProfileType::Mig1G20Gb,
            "mig-1g.23gb" => MigProfileType::Mig1G23Gb,
            "mig-1g.35gb" => MigProfileType::Mig1G35Gb,
            "mig-1g.45gb" => MigProfileType::Mig1G45Gb,
            "mig-1g.47gb" => MigProfileType::Mig1G47Gb,
            "mig-1g.5gb" => MigProfileType::Mig1G5Gb,
            "mig-2g.10gb" => MigProfileType::Mig2G10Gb,
            "mig-2g.20gb" => MigProfileType::Mig2G20Gb,
            "mig-2g.35gb" => MigProfileType::Mig2G35Gb,
            "mig-2g.45gb" => MigProfileType::Mig2G45Gb,
            "mig-2g.47gb" => MigProfileType::Mig2G47Gb,
            "mig-3g.20gb" => MigProfileType::Mig3G20Gb,
            "mig-3g.40gb" => MigProfileType::Mig3G40Gb,
            "mig-3g.71gb" => MigProfileType::Mig3G71Gb,
            "mig-3g.90gb" => MigProfileType::Mig3G90Gb,
            "mig-3g.93gb" => MigProfileType::Mig3G93Gb,
            "mig-4g.20gb" => MigProfileType::Mig4G20Gb,
            "mig-4g.40gb" => MigProfileType::Mig4G40Gb,
            "mig-4g.71gb" => MigProfileType::Mig4G71Gb,
            "mig-4g.90gb" => MigProfileType::Mig4G90Gb,
            "mig-4g.93gb" => MigProfileType::Mig4G93Gb,
            "mig-7g.141gb" => MigProfileType::Mig7G141Gb,
            "mig-7g.180gb" => MigProfileType::Mig7G180Gb,
            "mig-7g.186gb" => MigProfileType::Mig7G186Gb,
            "mig-7g.40gb" => MigProfileType::Mig7G40Gb,
            "mig-7g.80gb" => MigProfileType::Mig7G80Gb,
            other => MigProfileType::Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue(other.to_owned())),
        }
    }
}
impl ::std::str::FromStr for MigProfileType {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(MigProfileType::from(s))
    }
}
impl MigProfileType {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            MigProfileType::Mig1G10Gb => "mig-1g.10gb",
            MigProfileType::Mig1G18Gb => "mig-1g.18gb",
            MigProfileType::Mig1G20Gb => "mig-1g.20gb",
            MigProfileType::Mig1G23Gb => "mig-1g.23gb",
            MigProfileType::Mig1G35Gb => "mig-1g.35gb",
            MigProfileType::Mig1G45Gb => "mig-1g.45gb",
            MigProfileType::Mig1G47Gb => "mig-1g.47gb",
            MigProfileType::Mig1G5Gb => "mig-1g.5gb",
            MigProfileType::Mig2G10Gb => "mig-2g.10gb",
            MigProfileType::Mig2G20Gb => "mig-2g.20gb",
            MigProfileType::Mig2G35Gb => "mig-2g.35gb",
            MigProfileType::Mig2G45Gb => "mig-2g.45gb",
            MigProfileType::Mig2G47Gb => "mig-2g.47gb",
            MigProfileType::Mig3G20Gb => "mig-3g.20gb",
            MigProfileType::Mig3G40Gb => "mig-3g.40gb",
            MigProfileType::Mig3G71Gb => "mig-3g.71gb",
            MigProfileType::Mig3G90Gb => "mig-3g.90gb",
            MigProfileType::Mig3G93Gb => "mig-3g.93gb",
            MigProfileType::Mig4G20Gb => "mig-4g.20gb",
            MigProfileType::Mig4G40Gb => "mig-4g.40gb",
            MigProfileType::Mig4G71Gb => "mig-4g.71gb",
            MigProfileType::Mig4G90Gb => "mig-4g.90gb",
            MigProfileType::Mig4G93Gb => "mig-4g.93gb",
            MigProfileType::Mig7G141Gb => "mig-7g.141gb",
            MigProfileType::Mig7G180Gb => "mig-7g.180gb",
            MigProfileType::Mig7G186Gb => "mig-7g.186gb",
            MigProfileType::Mig7G40Gb => "mig-7g.40gb",
            MigProfileType::Mig7G80Gb => "mig-7g.80gb",
            MigProfileType::Unknown(value) => value.as_str(),
        }
    }
    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &[
            "mig-1g.10gb",
            "mig-1g.18gb",
            "mig-1g.20gb",
            "mig-1g.23gb",
            "mig-1g.35gb",
            "mig-1g.45gb",
            "mig-1g.47gb",
            "mig-1g.5gb",
            "mig-2g.10gb",
            "mig-2g.20gb",
            "mig-2g.35gb",
            "mig-2g.45gb",
            "mig-2g.47gb",
            "mig-3g.20gb",
            "mig-3g.40gb",
            "mig-3g.71gb",
            "mig-3g.90gb",
            "mig-3g.93gb",
            "mig-4g.20gb",
            "mig-4g.40gb",
            "mig-4g.71gb",
            "mig-4g.90gb",
            "mig-4g.93gb",
            "mig-7g.141gb",
            "mig-7g.180gb",
            "mig-7g.186gb",
            "mig-7g.40gb",
            "mig-7g.80gb",
        ]
    }
}
impl ::std::convert::AsRef<str> for MigProfileType {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl MigProfileType {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(value: &str) -> ::std::result::Result<Self, crate::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => ::std::result::Result::Err(crate::error::UnknownVariantError::new(value)),
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for MigProfileType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            MigProfileType::Mig1G10Gb => write!(f, "mig-1g.10gb"),
            MigProfileType::Mig1G18Gb => write!(f, "mig-1g.18gb"),
            MigProfileType::Mig1G20Gb => write!(f, "mig-1g.20gb"),
            MigProfileType::Mig1G23Gb => write!(f, "mig-1g.23gb"),
            MigProfileType::Mig1G35Gb => write!(f, "mig-1g.35gb"),
            MigProfileType::Mig1G45Gb => write!(f, "mig-1g.45gb"),
            MigProfileType::Mig1G47Gb => write!(f, "mig-1g.47gb"),
            MigProfileType::Mig1G5Gb => write!(f, "mig-1g.5gb"),
            MigProfileType::Mig2G10Gb => write!(f, "mig-2g.10gb"),
            MigProfileType::Mig2G20Gb => write!(f, "mig-2g.20gb"),
            MigProfileType::Mig2G35Gb => write!(f, "mig-2g.35gb"),
            MigProfileType::Mig2G45Gb => write!(f, "mig-2g.45gb"),
            MigProfileType::Mig2G47Gb => write!(f, "mig-2g.47gb"),
            MigProfileType::Mig3G20Gb => write!(f, "mig-3g.20gb"),
            MigProfileType::Mig3G40Gb => write!(f, "mig-3g.40gb"),
            MigProfileType::Mig3G71Gb => write!(f, "mig-3g.71gb"),
            MigProfileType::Mig3G90Gb => write!(f, "mig-3g.90gb"),
            MigProfileType::Mig3G93Gb => write!(f, "mig-3g.93gb"),
            MigProfileType::Mig4G20Gb => write!(f, "mig-4g.20gb"),
            MigProfileType::Mig4G40Gb => write!(f, "mig-4g.40gb"),
            MigProfileType::Mig4G71Gb => write!(f, "mig-4g.71gb"),
            MigProfileType::Mig4G90Gb => write!(f, "mig-4g.90gb"),
            MigProfileType::Mig4G93Gb => write!(f, "mig-4g.93gb"),
            MigProfileType::Mig7G141Gb => write!(f, "mig-7g.141gb"),
            MigProfileType::Mig7G180Gb => write!(f, "mig-7g.180gb"),
            MigProfileType::Mig7G186Gb => write!(f, "mig-7g.186gb"),
            MigProfileType::Mig7G40Gb => write!(f, "mig-7g.40gb"),
            MigProfileType::Mig7G80Gb => write!(f, "mig-7g.80gb"),
            MigProfileType::Unknown(value) => write!(f, "{value}"),
        }
    }
}
