// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListAgentRecommendationGenerations`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder) operation.
    /// This operation supports pagination; See [`into_paginator()`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::into_paginator).
    ///
    /// - The fluent builder is configurable:
    ///   - [`profile_arn(impl Into<String>)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::profile_arn) / [`set_profile_arn(Option<String>)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::set_profile_arn):<br>required: **true**<br><p>The Amazon Resource Name (ARN) of the optimization profile to list generation processes for.</p><br>
    ///   - [`recommendation_type(RecommendationType)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::recommendation_type) / [`set_recommendation_type(Option<RecommendationType>)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::set_recommendation_type):<br>required: **false**<br><p>Optional filter by recommendation type.</p><br>
    ///   - [`max_results(i32)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::max_results) / [`set_max_results(Option<i32>)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::set_max_results):<br>required: **false**<br><p>The maximum number of generation processes to return in a single response.</p><br>
    ///   - [`next_token(impl Into<String>)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::next_token) / [`set_next_token(Option<String>)`](crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::set_next_token):<br>required: **false**<br><p>A pagination token returned from a previous call to continue retrieving results.</p><br>
    /// - On success, responds with [`ListAgentRecommendationGenerationsOutput`](crate::operation::list_agent_recommendation_generations::ListAgentRecommendationGenerationsOutput) with field(s):
    ///   - [`items(Vec::<AgentRecommendationGenerationSummary>)`](crate::operation::list_agent_recommendation_generations::ListAgentRecommendationGenerationsOutput::items): <p>A list of recommendation generation summaries.</p>
    ///   - [`next_token(Option<String>)`](crate::operation::list_agent_recommendation_generations::ListAgentRecommendationGenerationsOutput::next_token): <p>A pagination token to retrieve the next set of results, if available.</p>
    /// - On failure, responds with [`SdkError<ListAgentRecommendationGenerationsError>`](crate::operation::list_agent_recommendation_generations::ListAgentRecommendationGenerationsError)
    pub fn list_agent_recommendation_generations(
        &self,
    ) -> crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder {
        crate::operation::list_agent_recommendation_generations::builders::ListAgentRecommendationGenerationsFluentBuilder::new(self.handle.clone())
    }
}
