[package]
name = "smithy-query"
version = "0.26.0-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
description = "AWSQuery and EC2Query Smithy protocol logic for smithy-rs."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
urlencoding = "1.3"
smithy-types = { path = "../smithy-types" }