// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_named_entity_definition(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::NamedEntityDefinition,
) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.field_name {
        object.key("FieldName").string(var_1.as_str());
    }
    if let Some(var_2) = &input.property_name {
        object.key("PropertyName").string(var_2.as_str());
    }
    if let Some(var_3) = &input.property_role {
        object.key("PropertyRole").string(var_3.as_str());
    }
    if let Some(var_4) = &input.property_usage {
        object.key("PropertyUsage").string(var_4.as_str());
    }
    if let Some(var_5) = &input.metric {
        #[allow(unused_mut)]
        let mut object_6 = object.key("Metric").start_object();
        crate::protocol_serde::shape_named_entity_definition_metric::ser_named_entity_definition_metric(&mut object_6, var_5)?;
        object_6.finish();
    }
    Ok(())
}

pub(crate) fn de_named_entity_definition<'a, I>(
    tokens: &mut ::std::iter::Peekable<I>,
) -> Result<Option<crate::types::NamedEntityDefinition>, ::aws_smithy_json::deserialize::error::DeserializeError>
where
    I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>>,
{
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            #[allow(unused_mut)]
            let mut builder = crate::types::builders::NamedEntityDefinitionBuilder::default();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => match key.to_unescaped()?.as_ref() {
                        "FieldName" => {
                            builder = builder.set_field_name(
                                ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                                    .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                                    .transpose()?,
                            );
                        }
                        "PropertyName" => {
                            builder = builder.set_property_name(
                                ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                                    .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                                    .transpose()?,
                            );
                        }
                        "PropertyRole" => {
                            builder = builder.set_property_role(
                                ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                                    .map(|s| s.to_unescaped().map(|u| crate::types::PropertyRole::from(u.as_ref())))
                                    .transpose()?,
                            );
                        }
                        "PropertyUsage" => {
                            builder = builder.set_property_usage(
                                ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                                    .map(|s| s.to_unescaped().map(|u| crate::types::PropertyUsage::from(u.as_ref())))
                                    .transpose()?,
                            );
                        }
                        "Metric" => {
                            builder = builder
                                .set_metric(crate::protocol_serde::shape_named_entity_definition_metric::de_named_entity_definition_metric(tokens)?);
                        }
                        _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
                    },
                    other => {
                        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!(
                            "expected object key or end object, found: {:?}",
                            other
                        )))
                    }
                }
            }
            Ok(Some(builder.build()))
        }
        _ => Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "expected start object or null",
        )),
    }
}
