[package]
name = "smithy-eventstream"
edition = "2018"
version = "0.26.0-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
description = "Event stream logic for smithy-rs."
keywords = []
categories = []
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
autobins = true
autoexamples = true
autotests = true
autobenches = true
publish = true

[dependencies]
bytes = "1"
crc32fast = "1"

[dependencies.arbitrary]
version = "1"
features = ["derive"]
optional = true

[dependencies.smithy-types]
version = "0.26.0-alpha"
path = "../smithy-types"
features = []
optional = false

[dev-dependencies]
bytes-utils = "0.1"

[features]
default = []
derive-arbitrary = ["arbitrary"]
