#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script contains additional CI checks to run for this specific package

set -e

echo "### Testing feature powerset"
cargo hack test --feature-powerset
