// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DescribeInsight`](crate::operation::describe_insight::builders::DescribeInsightFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`cluster_name(impl Into<String>)`](crate::operation::describe_insight::builders::DescribeInsightFluentBuilder::cluster_name) / [`set_cluster_name(Option<String>)`](crate::operation::describe_insight::builders::DescribeInsightFluentBuilder::set_cluster_name):<br>required: **true**<br><p>The name of the cluster to describe the insight for.</p><br>
    ///   - [`id(impl Into<String>)`](crate::operation::describe_insight::builders::DescribeInsightFluentBuilder::id) / [`set_id(Option<String>)`](crate::operation::describe_insight::builders::DescribeInsightFluentBuilder::set_id):<br>required: **true**<br><p>The identity of the insight to describe.</p><br>
    /// - On success, responds with [`DescribeInsightOutput`](crate::operation::describe_insight::DescribeInsightOutput) with field(s):
    ///   - [`insight(Option<Insight>)`](crate::operation::describe_insight::DescribeInsightOutput::insight): <p>The full description of the insight.</p>
    /// - On failure, responds with [`SdkError<DescribeInsightError>`](crate::operation::describe_insight::DescribeInsightError)
    pub fn describe_insight(&self) -> crate::operation::describe_insight::builders::DescribeInsightFluentBuilder {
        crate::operation::describe_insight::builders::DescribeInsightFluentBuilder::new(self.handle.clone())
    }
}
