[package]
name = "snowball-code-examples"
version = "0.1.0"
authors = ["Landon James <lnj@amazon.com>", "Doug Schwartz <dougsch@amazon.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-snowball = { path = "../../snowball" }
aws-types = { path = "../../aws-types" }
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = "0.2.18"
