[package]
name = "snowball-code-examples"
version = "0.1.0"
authors = ["Landon James <lnj@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"]}
aws-sdk-snowball = { path = "../../snowball" }
aws-types = { path = "../../aws-types" }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
