// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_get_attachment_download_link_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::get_attachment_download_link::GetAttachmentDownloadLinkInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.attachment_id {
        object.key("attachmentId").string(var_1.as_str());
    }
    if let Some(var_2) = &input.dry_run {
        object.key("dryRun").boolean(*var_2);
    }
    Ok(())
}
