// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Describes a rule match.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum RuleMatch {
    /// <p>The HTTP criteria that a rule must match.</p>
    HttpMatch(crate::types::HttpMatch),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl RuleMatch {
    #[allow(irrefutable_let_patterns)]
    /// Tries to convert the enum instance into [`HttpMatch`](crate::types::RuleMatch::HttpMatch), extracting the inner [`HttpMatch`](crate::types::HttpMatch).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_http_match(&self) -> ::std::result::Result<&crate::types::HttpMatch, &Self> {
        if let RuleMatch::HttpMatch(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`HttpMatch`](crate::types::RuleMatch::HttpMatch).
    pub fn is_http_match(&self) -> bool {
        self.as_http_match().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}

