// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteServiceInput  {
    /// <p>The ID or Amazon Resource Name (ARN) of the service.</p>
    pub service_identifier: ::std::option::Option<::std::string::String>,
}
impl  DeleteServiceInput  {
    /// <p>The ID or Amazon Resource Name (ARN) of the service.</p>
    pub fn service_identifier(&self) -> ::std::option::Option<& str> {
        self.service_identifier.as_deref()
    }
}
impl DeleteServiceInput {
    /// Creates a new builder-style object to manufacture [`DeleteServiceInput`](crate::operation::delete_service::DeleteServiceInput).
    pub fn builder() -> crate::operation::delete_service::builders::DeleteServiceInputBuilder {
        crate::operation::delete_service::builders::DeleteServiceInputBuilder::default()
    }
}

/// A builder for [`DeleteServiceInput`](crate::operation::delete_service::DeleteServiceInput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct DeleteServiceInputBuilder {
    pub(crate) service_identifier: ::std::option::Option<::std::string::String>,
}
impl DeleteServiceInputBuilder {
    /// <p>The ID or Amazon Resource Name (ARN) of the service.</p>
    /// This field is required.
    pub fn service_identifier(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.service_identifier = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID or Amazon Resource Name (ARN) of the service.</p>
    pub fn set_service_identifier(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.service_identifier = input; self
    }
    /// <p>The ID or Amazon Resource Name (ARN) of the service.</p>
    pub fn get_service_identifier(&self) -> &::std::option::Option<::std::string::String> {
        &self.service_identifier
    }
    /// Consumes the builder and constructs a [`DeleteServiceInput`](crate::operation::delete_service::DeleteServiceInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::delete_service::DeleteServiceInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::delete_service::DeleteServiceInput {
                service_identifier: self.service_identifier
                ,
            }
        )
    }
}

