[package]
name = "aws-sdk-s3"
edition = "2018"
version = "0.0.21-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "AWS SDK for Amazon Simple Storage Service"
readme = "README.md"
keywords = []
categories = []
license = "Apache-2.0"
repository = "https://github.com/awslabs/aws-sdk-rust"
autobins = true
autoexamples = true
autotests = true
autobenches = true
publish = true
[dependencies.aws-auth]
version = "0.0.21-alpha"
path = "..//aws-auth"
features = []
optional = false

[dependencies.aws-endpoint]
version = "0.0.21-alpha"
path = "..//aws-endpoint"
features = []
optional = false

[dependencies.aws-http]
version = "0.0.21-alpha"
path = "..//aws-http"
features = []
optional = false

[dependencies.aws-hyper]
version = "0.0.21-alpha"
path = "..//aws-hyper"
features = []
optional = true

[dependencies.aws-sig-auth]
version = "0.0.21-alpha"
path = "..//aws-sig-auth"
features = ["sign-eventstream"]
optional = false

[dependencies.aws-sigv4]
version = "0.0.21-alpha"
path = "..//aws-sigv4"
features = []
optional = false

[dependencies.aws-types]
version = "0.0.21-alpha"
path = "..//aws-types"
features = []
optional = false

[dependencies.bytes]
version = "1"
features = []
optional = false

[dependencies.http]
version = "0.2"
features = []
optional = false

[dependencies.md5]
version = "0.7"
features = []
optional = false

[dependencies.smithy-client]
version = "0.26.0-alpha"
path = "..//smithy-client"
features = []
optional = true

[dependencies.smithy-eventstream]
version = "0.26.0-alpha"
path = "..//smithy-eventstream"
features = []
optional = false

[dependencies.smithy-http]
version = "0.26.0-alpha"
path = "..//smithy-http"
features = ["event-stream"]
optional = false

[dependencies.smithy-types]
version = "0.26.0-alpha"
path = "..//smithy-types"
features = []
optional = false

[dependencies.smithy-xml]
version = "0.26.0-alpha"
path = "..//smithy-xml"
features = []
optional = false

[dependencies.tower]
version = "0.4"
features = []
optional = true
[dev-dependencies.serde_json]
version = "1"
features = []
optional = false

[dev-dependencies.smithy-client]
version = "0.26.0-alpha"
path = "..//smithy-client"
features = ["test-util"]
optional = false

[dev-dependencies.smithy-protocol-test]
version = "0.26.0-alpha"
path = "..//smithy-protocol-test"
features = []
optional = false

[dev-dependencies.tokio]
version = "1"
features = ["macros", "test-util", "rt"]
optional = false

[features]
client = ["aws-hyper", "smithy-client", "tower"]
default = ["client", "rustls"]
native-tls = ["aws-hyper/native-tls"]
rustls = ["aws-hyper/rustls"]
