[package]
name = "smithy-client"
edition = "2018"
version = "0.26.0-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Client for smithy-rs."
keywords = []
categories = []
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
autobins = true
autoexamples = true
autotests = true
autobenches = true
publish = true

[dependencies]
bytes = "1"
fastrand = "1.4.0"
http = "0.2.3"
http-body = "0.4.0"
pin-project = "1"
pin-project-lite = "0.2.7"
tracing = "0.1"

[dependencies.hyper]
version = "0.14.2"
features = ["client", "http2"]
optional = true

[dependencies.hyper-rustls]
version = "0.22.1"
features = ["rustls-native-certs"]
optional = true

[dependencies.hyper-tls]
version = "0.5.0"
features = []
optional = true

[dependencies.lazy_static]
version = "1"
features = []
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.smithy-async]
version = "0.26.0-alpha"
path = "../smithy-async"
features = []
optional = false

[dependencies.smithy-http]
version = "0.26.0-alpha"
path = "../smithy-http"
features = []
optional = false

[dependencies.smithy-http-tower]
version = "0.26.0-alpha"
path = "../smithy-http-tower"
features = []
optional = false

[dependencies.smithy-protocol-test]
version = "0.26.0-alpha"
path = "../smithy-protocol-test"
features = []
optional = true

[dependencies.smithy-types]
version = "0.26.0-alpha"
path = "../smithy-types"
features = []
optional = false

[dependencies.tokio]
version = "1"
features = ["time"]
optional = false

[dependencies.tower]
version = "0.4.6"
features = ["util", "retry"]
optional = false

[dev-dependencies]
serde_json = "1"
tower-test = "0.4.0"

[dev-dependencies.serde]
version = "1"
features = ["derive"]
optional = false

[dev-dependencies.tokio]
version = "1"
features = ["full", "test-util"]
optional = false

[features]
default = ["hyper", "rustls", "rt-tokio"]
native-tls = ["hyper", "hyper-tls", "rt-tokio"]
rt-tokio = ["smithy-async/rt-tokio"]
rustls = ["hyper", "hyper-rustls", "rt-tokio", "lazy_static"]
test-util = ["smithy-protocol-test", "serde/derive"]
