#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script contains additional CI checks to run for this specific package

set -e

echo "### Testing unstable custom rustls crypto provider"
# Enabling ring because the tests use it as the "custom" provider, and it transitively enables __rustls
RUSTFLAGS="--cfg aws_sdk_unstable" cargo test --features rustls-ring
