[[bin]]
name = "scenario"

[package]
name = "glue-code-examples"
version = "0.1.0"
authors = ["David Souther <davidsouther+github@gmail.com>"]
edition = "2021"
description = "MVP Scenario to show many features of the Rust AWS Glue SDK. https://github.com/awsdocs/aws-doc-sdk-examples/issues/2941"
publish = false

[dependencies]
tracing = "0.1.37"
async_once = "0.2.6"
lazy_static = "1.4.0"
clap_lex = "=0.3.0"
thiserror = "1.0.37"
secrecy = "0.8.0"
futures = "0.3.25"
tracing-bunyan-formatter = "0.3.4"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.54.1"

[dependencies.aws-sdk-glue]
path = "../../sdk/glue"
version = "0.26.0"

[dependencies.aws-sdk-s3]
path = "../../sdk/s3"
version = "0.26.0"

[dependencies.aws-http]
path = "../../sdk/aws-http"
version = "0.54.1"

[dependencies.aws-smithy-client]
features = ["client-hyper", "rustls", "rt-tokio"]
path = "../../sdk/aws-smithy-client"
version = "0.54.1"

[dependencies.aws-smithy-http]
features = ["rt-tokio"]
path = "../../sdk/aws-smithy-http"
version = "0.54.1"

[dependencies.aws-smithy-types]
path = "../../sdk/aws-smithy-types"
version = "0.54.1"

[dependencies.aws-types]
path = "../../sdk/aws-types"
version = "0.54.1"

[dependencies.tokio]
version = "1.20.1"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.15"
features = ["env-filter"]

[dependencies.clap]
version = "~4.0.18"
features = ["derive"]

[dependencies.uuid]
version = "1.2.1"
features = ["v4"]
