[[bin]]
name = "intro"
path = "src/intro.rs"

[package]
name = "testing-examples"
version = "0.1.0"
authors = ["John Disanti <jdisanti@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.51"
serde_json = "1"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.54.1"

[dependencies.aws-sdk-s3]
path = "../../sdk/s3"
version = "0.25.0"

[dependencies.aws-smithy-client]
features = ["test-util"]
path = "../../sdk/aws-smithy-client"
version = "0.54.1"

[dependencies.aws-smithy-http]
path = "../../sdk/aws-smithy-http"
version = "0.54.1"

[dependencies.aws-types]
path = "../../sdk/aws-types"
version = "0.54.1"

[dependencies.aws-credential-types]
features = ["hardcoded-credentials"]
path = "../../sdk/aws-credential-types"
version = "0.54.1"

[dependencies.tokio]
version = "1.20.1"
features = ["full"]

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.15"
features = ["env-filter"]
