[package]
name = "ebs"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"]}
aws-sdk-ebs = { path = "../../ebs" }
aws-sdk-ec2 = { path = "../../ec2" }
sha2 = "0.9.5"
base64 = "0.13.0"
tracing-subscriber = "0.2.19"
