// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>An error that occurred while creating a firewall rule in a batch operation.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct BatchCreateFirewallRuleError {
    /// <p>The firewall rule entry that caused the error.</p>
    pub firewall_rule: ::std::option::Option<crate::types::CreateFirewallRuleEntry>,
    /// <p>The error code for the failure.</p>
    pub code: ::std::option::Option<::std::string::String>,
    /// <p>A message that provides details about the error.</p>
    pub message: ::std::option::Option<::std::string::String>,
}
impl BatchCreateFirewallRuleError {
    /// <p>The firewall rule entry that caused the error.</p>
    pub fn firewall_rule(&self) -> ::std::option::Option<&crate::types::CreateFirewallRuleEntry> {
        self.firewall_rule.as_ref()
    }
    /// <p>The error code for the failure.</p>
    pub fn code(&self) -> ::std::option::Option<&str> {
        self.code.as_deref()
    }
    /// <p>A message that provides details about the error.</p>
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }
}
impl BatchCreateFirewallRuleError {
    /// Creates a new builder-style object to manufacture [`BatchCreateFirewallRuleError`](crate::types::BatchCreateFirewallRuleError).
    pub fn builder() -> crate::types::builders::BatchCreateFirewallRuleErrorBuilder {
        crate::types::builders::BatchCreateFirewallRuleErrorBuilder::default()
    }
}

/// A builder for [`BatchCreateFirewallRuleError`](crate::types::BatchCreateFirewallRuleError).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct BatchCreateFirewallRuleErrorBuilder {
    pub(crate) firewall_rule: ::std::option::Option<crate::types::CreateFirewallRuleEntry>,
    pub(crate) code: ::std::option::Option<::std::string::String>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
}
impl BatchCreateFirewallRuleErrorBuilder {
    /// <p>The firewall rule entry that caused the error.</p>
    pub fn firewall_rule(mut self, input: crate::types::CreateFirewallRuleEntry) -> Self {
        self.firewall_rule = ::std::option::Option::Some(input);
        self
    }
    /// <p>The firewall rule entry that caused the error.</p>
    pub fn set_firewall_rule(mut self, input: ::std::option::Option<crate::types::CreateFirewallRuleEntry>) -> Self {
        self.firewall_rule = input;
        self
    }
    /// <p>The firewall rule entry that caused the error.</p>
    pub fn get_firewall_rule(&self) -> &::std::option::Option<crate::types::CreateFirewallRuleEntry> {
        &self.firewall_rule
    }
    /// <p>The error code for the failure.</p>
    pub fn code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.code = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The error code for the failure.</p>
    pub fn set_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.code = input;
        self
    }
    /// <p>The error code for the failure.</p>
    pub fn get_code(&self) -> &::std::option::Option<::std::string::String> {
        &self.code
    }
    /// <p>A message that provides details about the error.</p>
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>A message that provides details about the error.</p>
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    /// <p>A message that provides details about the error.</p>
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Consumes the builder and constructs a [`BatchCreateFirewallRuleError`](crate::types::BatchCreateFirewallRuleError).
    pub fn build(self) -> crate::types::BatchCreateFirewallRuleError {
        crate::types::BatchCreateFirewallRuleError {
            firewall_rule: self.firewall_rule,
            code: self.code,
            message: self.message,
        }
    }
}
