[package]
name = "ec2-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../aws-config" }
aws-sdk-ec2 = { package = "aws-sdk-ec2", path = "../../ec2" }
tokio = { version = "1", features = ["full"]}
actix-rt = "*"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = "0.2.18"
