[package]
name = "ec2-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../aws-config" }
tokio = { version = "1", features = ["full"]}
aws-sdk-ec2 = { path = "../../ec2" }
