#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script contains additional CI checks to run for this specific package

set -e

echo "### Checking for external types in public API"
cargo "+${RUST_NIGHTLY_VERSION:-nightly}" api-linter --all-features --config api-linter.toml

echo "### Checking for duplicate dependency versions in the normal dependency graph with all features enabled"
cargo tree -d --edges normal --all-features

# `aws-config` is not part of the `rust-runtime` workspace. As a result it is not run through
# `check-rust-runtimes-and-tools` and does not get `cargo test --all-features` prior to this point. As a result we do
# not apply `--exclude-all-features` here.
echo "### Testing every combination of features"
cargo hack test --feature-powerset

echo "### Checking that compiling with the minimal versions succeeds"
cargo "+${RUST_NIGHTLY_VERSION:-nightly}" minimal-versions check --all-features
