// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::extend_transaction::_extend_transaction_output::ExtendTransactionOutputBuilder;

pub use crate::operation::extend_transaction::_extend_transaction_input::ExtendTransactionInputBuilder;

impl ExtendTransactionInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::extend_transaction::ExtendTransactionOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::extend_transaction::ExtendTransactionError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let mut fluent_builder = client.extend_transaction();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `ExtendTransaction`.
///
/// <p>Indicates to the service that the specified transaction is still active and should not be treated as idle and aborted.</p>
/// <p>Write transactions that remain idle for a long period are automatically aborted unless explicitly extended.</p>
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct ExtendTransactionFluentBuilder {
    handle: ::std::sync::Arc<crate::client::Handle>,
    inner: crate::operation::extend_transaction::builders::ExtendTransactionInputBuilder,
    config_override: ::std::option::Option<crate::config::Builder>,
}
impl
    crate::client::customize::internal::CustomizableSend<
        crate::operation::extend_transaction::ExtendTransactionOutput,
        crate::operation::extend_transaction::ExtendTransactionError,
    > for ExtendTransactionFluentBuilder
{
    fn send(
        self,
        config_override: crate::config::Builder,
    ) -> crate::client::customize::internal::BoxFuture<
        crate::client::customize::internal::SendResult<
            crate::operation::extend_transaction::ExtendTransactionOutput,
            crate::operation::extend_transaction::ExtendTransactionError,
        >,
    > {
        ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
    }
}
impl ExtendTransactionFluentBuilder {
    /// Creates a new `ExtendTransaction`.
    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
        Self {
            handle,
            inner: ::std::default::Default::default(),
            config_override: ::std::option::Option::None,
        }
    }
    /// Access the ExtendTransaction as a reference.
    pub fn as_input(&self) -> &crate::operation::extend_transaction::builders::ExtendTransactionInputBuilder {
        &self.inner
    }
    /// Sends the request and returns the response.
    ///
    /// If an error occurs, an `SdkError` will be returned with additional details that
    /// can be matched against.
    ///
    /// By default, any retryable failures will be retried twice. Retry behavior
    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
    /// set when configuring the client.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::extend_transaction::ExtendTransactionOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::extend_transaction::ExtendTransactionError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let input = self
            .inner
            .build()
            .map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
        let runtime_plugins = crate::operation::extend_transaction::ExtendTransaction::operation_runtime_plugins(
            self.handle.runtime_plugins.clone(),
            &self.handle.conf,
            self.config_override,
        );
        crate::operation::extend_transaction::ExtendTransaction::orchestrate(&runtime_plugins, input).await
    }

    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
    pub fn customize(
        self,
    ) -> crate::client::customize::CustomizableOperation<
        crate::operation::extend_transaction::ExtendTransactionOutput,
        crate::operation::extend_transaction::ExtendTransactionError,
        Self,
    > {
        crate::client::customize::CustomizableOperation::new(self)
    }
    pub(crate) fn config_override(mut self, config_override: impl Into<crate::config::Builder>) -> Self {
        self.set_config_override(Some(config_override.into()));
        self
    }

    pub(crate) fn set_config_override(&mut self, config_override: Option<crate::config::Builder>) -> &mut Self {
        self.config_override = config_override;
        self
    }
    /// <p>The transaction to extend.</p>
    pub fn transaction_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.transaction_id(input.into());
        self
    }
    /// <p>The transaction to extend.</p>
    pub fn set_transaction_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_transaction_id(input);
        self
    }
    /// <p>The transaction to extend.</p>
    pub fn get_transaction_id(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_transaction_id()
    }
}
