[package]
name = "aws-sdk-quicksight"
edition = "2018"
version = "0.0.21-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "AWS SDK for Amazon QuickSight"
readme = "README.md"
keywords = []
categories = []
license = "Apache-2.0"
repository = "https://github.com/awslabs/aws-sdk-rust"
autobins = true
autoexamples = true
autotests = true
autobenches = true
publish = true
[dependencies.aws-auth]
version = "0.0.21-alpha"
path = "..//aws-auth"
features = []
optional = false

[dependencies.aws-endpoint]
version = "0.0.21-alpha"
path = "..//aws-endpoint"
features = []
optional = false

[dependencies.aws-http]
version = "0.0.21-alpha"
path = "..//aws-http"
features = []
optional = false

[dependencies.aws-hyper]
version = "0.0.21-alpha"
path = "..//aws-hyper"
features = []
optional = true

[dependencies.aws-sig-auth]
version = "0.0.21-alpha"
path = "..//aws-sig-auth"
features = []
optional = false

[dependencies.aws-types]
version = "0.0.21-alpha"
path = "..//aws-types"
features = []
optional = false

[dependencies.bytes]
version = "1"
features = []
optional = false

[dependencies.http]
version = "0.2"
features = []
optional = false

[dependencies.smithy-client]
version = "0.26.0-alpha"
path = "..//smithy-client"
features = []
optional = true

[dependencies.smithy-http]
version = "0.26.0-alpha"
path = "..//smithy-http"
features = []
optional = false

[dependencies.smithy-json]
version = "0.26.0-alpha"
path = "..//smithy-json"
features = []
optional = false

[dependencies.smithy-types]
version = "0.26.0-alpha"
path = "..//smithy-types"
features = []
optional = false

[features]
client = ["aws-hyper", "smithy-client"]
default = ["client", "rustls"]
native-tls = ["aws-hyper/native-tls"]
rustls = ["aws-hyper/rustls"]
