// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateDataAccessorOutput {
    /// <p>The unique identifier of the created data accessor.</p>
    pub data_accessor_id: ::std::string::String,
    /// <p>The Amazon Resource Name (ARN) of the IAM Identity Center application created for this data accessor.</p>
    pub idc_application_arn: ::std::string::String,
    /// <p>The Amazon Resource Name (ARN) of the created data accessor.</p>
    pub data_accessor_arn: ::std::string::String,
    _request_id: Option<String>,
}
impl CreateDataAccessorOutput {
    /// <p>The unique identifier of the created data accessor.</p>
    pub fn data_accessor_id(&self) -> &str {
        use std::ops::Deref;
        self.data_accessor_id.deref()
    }
    /// <p>The Amazon Resource Name (ARN) of the IAM Identity Center application created for this data accessor.</p>
    pub fn idc_application_arn(&self) -> &str {
        use std::ops::Deref;
        self.idc_application_arn.deref()
    }
    /// <p>The Amazon Resource Name (ARN) of the created data accessor.</p>
    pub fn data_accessor_arn(&self) -> &str {
        use std::ops::Deref;
        self.data_accessor_arn.deref()
    }
}
impl ::aws_types::request_id::RequestId for CreateDataAccessorOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl CreateDataAccessorOutput {
    /// Creates a new builder-style object to manufacture [`CreateDataAccessorOutput`](crate::operation::create_data_accessor::CreateDataAccessorOutput).
    pub fn builder() -> crate::operation::create_data_accessor::builders::CreateDataAccessorOutputBuilder {
        crate::operation::create_data_accessor::builders::CreateDataAccessorOutputBuilder::default()
    }
}

/// A builder for [`CreateDataAccessorOutput`](crate::operation::create_data_accessor::CreateDataAccessorOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateDataAccessorOutputBuilder {
    pub(crate) data_accessor_id: ::std::option::Option<::std::string::String>,
    pub(crate) idc_application_arn: ::std::option::Option<::std::string::String>,
    pub(crate) data_accessor_arn: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl CreateDataAccessorOutputBuilder {
    /// <p>The unique identifier of the created data accessor.</p>
    /// This field is required.
    pub fn data_accessor_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.data_accessor_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The unique identifier of the created data accessor.</p>
    pub fn set_data_accessor_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.data_accessor_id = input;
        self
    }
    /// <p>The unique identifier of the created data accessor.</p>
    pub fn get_data_accessor_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.data_accessor_id
    }
    /// <p>The Amazon Resource Name (ARN) of the IAM Identity Center application created for this data accessor.</p>
    /// This field is required.
    pub fn idc_application_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idc_application_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the IAM Identity Center application created for this data accessor.</p>
    pub fn set_idc_application_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idc_application_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the IAM Identity Center application created for this data accessor.</p>
    pub fn get_idc_application_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.idc_application_arn
    }
    /// <p>The Amazon Resource Name (ARN) of the created data accessor.</p>
    /// This field is required.
    pub fn data_accessor_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.data_accessor_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the created data accessor.</p>
    pub fn set_data_accessor_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.data_accessor_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the created data accessor.</p>
    pub fn get_data_accessor_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.data_accessor_arn
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`CreateDataAccessorOutput`](crate::operation::create_data_accessor::CreateDataAccessorOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`data_accessor_id`](crate::operation::create_data_accessor::builders::CreateDataAccessorOutputBuilder::data_accessor_id)
    /// - [`idc_application_arn`](crate::operation::create_data_accessor::builders::CreateDataAccessorOutputBuilder::idc_application_arn)
    /// - [`data_accessor_arn`](crate::operation::create_data_accessor::builders::CreateDataAccessorOutputBuilder::data_accessor_arn)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::create_data_accessor::CreateDataAccessorOutput, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::operation::create_data_accessor::CreateDataAccessorOutput {
            data_accessor_id: self.data_accessor_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "data_accessor_id",
                    "data_accessor_id was not specified but it is required when building CreateDataAccessorOutput",
                )
            })?,
            idc_application_arn: self.idc_application_arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "idc_application_arn",
                    "idc_application_arn was not specified but it is required when building CreateDataAccessorOutput",
                )
            })?,
            data_accessor_arn: self.data_accessor_arn.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "data_accessor_arn",
                    "data_accessor_arn was not specified but it is required when building CreateDataAccessorOutput",
                )
            })?,
            _request_id: self._request_id,
        })
    }
}
