// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DescribeAgentStatus`](crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`instance_id(impl Into<String>)`](crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder::instance_id) / [`set_instance_id(Option<String>)`](crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder::set_instance_id):<br>required: **true**<br><p>The identifier of the Amazon Connect instance. You can <a href="https://docs.aws.amazon.com/connect/latest/adminguide/find-instance-arn.html">find the instance ID</a> in the Amazon Resource Name (ARN) of the instance.</p><br>
    ///   - [`agent_status_id(impl Into<String>)`](crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder::agent_status_id) / [`set_agent_status_id(Option<String>)`](crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder::set_agent_status_id):<br>required: **true**<br><p>The identifier for the agent status.</p><br>
                            /// - On success, responds with [`DescribeAgentStatusOutput`](crate::operation::describe_agent_status::DescribeAgentStatusOutput) with field(s):
    ///   - [`agent_status(Option<AgentStatus>)`](crate::operation::describe_agent_status::DescribeAgentStatusOutput::agent_status): <p>The agent status.</p>
                            /// - On failure, responds with [`SdkError<DescribeAgentStatusError>`](crate::operation::describe_agent_status::DescribeAgentStatusError)
    pub fn describe_agent_status(&self) -> crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder {
                                crate::operation::describe_agent_status::builders::DescribeAgentStatusFluentBuilder::new(self.handle.clone())
                            }
}

