// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct UpdateDataSourceInput  {
    /// <p>The Amazon Web Services account ID.</p>
    #[doc(hidden)]
    pub aws_account_id: std::option::Option<std::string::String>,
    /// <p>The ID of the data source. This ID is unique per Amazon Web Services Region for each Amazon Web Services account. </p>
    #[doc(hidden)]
    pub data_source_id: std::option::Option<std::string::String>,
    /// <p>A display name for the data source.</p>
    #[doc(hidden)]
    pub name: std::option::Option<std::string::String>,
    /// <p>The parameters that Amazon QuickSight uses to connect to your underlying source.</p>
    #[doc(hidden)]
    pub data_source_parameters: std::option::Option<crate::types::DataSourceParameters>,
    /// <p>The credentials that Amazon QuickSight that uses to connect to your underlying source. Currently, only credentials based on user name and password are supported.</p>
    #[doc(hidden)]
    pub credentials: std::option::Option<crate::types::DataSourceCredentials>,
    /// <p>Use this parameter only when you want Amazon QuickSight to use a VPC connection when connecting to your underlying source.</p>
    #[doc(hidden)]
    pub vpc_connection_properties: std::option::Option<crate::types::VpcConnectionProperties>,
    /// <p>Secure Socket Layer (SSL) properties that apply when Amazon QuickSight connects to your underlying source.</p>
    #[doc(hidden)]
    pub ssl_properties: std::option::Option<crate::types::SslProperties>,
}
impl UpdateDataSourceInput {
    /// <p>The Amazon Web Services account ID.</p>
    pub fn aws_account_id(&self) -> std::option::Option<& str> {
        self.aws_account_id.as_deref()
    }
    /// <p>The ID of the data source. This ID is unique per Amazon Web Services Region for each Amazon Web Services account. </p>
    pub fn data_source_id(&self) -> std::option::Option<& str> {
        self.data_source_id.as_deref()
    }
    /// <p>A display name for the data source.</p>
    pub fn name(&self) -> std::option::Option<& str> {
        self.name.as_deref()
    }
    /// <p>The parameters that Amazon QuickSight uses to connect to your underlying source.</p>
    pub fn data_source_parameters(&self) -> std::option::Option<& crate::types::DataSourceParameters> {
        self.data_source_parameters.as_ref()
    }
    /// <p>The credentials that Amazon QuickSight that uses to connect to your underlying source. Currently, only credentials based on user name and password are supported.</p>
    pub fn credentials(&self) -> std::option::Option<& crate::types::DataSourceCredentials> {
        self.credentials.as_ref()
    }
    /// <p>Use this parameter only when you want Amazon QuickSight to use a VPC connection when connecting to your underlying source.</p>
    pub fn vpc_connection_properties(&self) -> std::option::Option<& crate::types::VpcConnectionProperties> {
        self.vpc_connection_properties.as_ref()
    }
    /// <p>Secure Socket Layer (SSL) properties that apply when Amazon QuickSight connects to your underlying source.</p>
    pub fn ssl_properties(&self) -> std::option::Option<& crate::types::SslProperties> {
        self.ssl_properties.as_ref()
    }
}
impl  std::fmt::Debug for UpdateDataSourceInput  {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("UpdateDataSourceInput");
        formatter.field("aws_account_id", &self.aws_account_id);
        formatter.field("data_source_id", &self.data_source_id);
        formatter.field("name", &self.name);
        formatter.field("data_source_parameters", &self.data_source_parameters);
        formatter.field("credentials", &"*** Sensitive Data Redacted ***");
        formatter.field("vpc_connection_properties", &self.vpc_connection_properties);
        formatter.field("ssl_properties", &self.ssl_properties);
        formatter.finish()
    }
}
impl UpdateDataSourceInput {
    /// Creates a new builder-style object to manufacture [`UpdateDataSourceInput`](crate::operation::update_data_source::UpdateDataSourceInput).
    pub fn builder() -> crate::operation::update_data_source::builders::UpdateDataSourceInputBuilder {
        crate::operation::update_data_source::builders::UpdateDataSourceInputBuilder::default()
    }
}

/// A builder for [`UpdateDataSourceInput`](crate::operation::update_data_source::UpdateDataSourceInput).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default)]
pub struct UpdateDataSourceInputBuilder {
    pub(crate) aws_account_id: std::option::Option<std::string::String>,
    pub(crate) data_source_id: std::option::Option<std::string::String>,
    pub(crate) name: std::option::Option<std::string::String>,
    pub(crate) data_source_parameters: std::option::Option<crate::types::DataSourceParameters>,
    pub(crate) credentials: std::option::Option<crate::types::DataSourceCredentials>,
    pub(crate) vpc_connection_properties: std::option::Option<crate::types::VpcConnectionProperties>,
    pub(crate) ssl_properties: std::option::Option<crate::types::SslProperties>,
}
impl UpdateDataSourceInputBuilder {
    /// <p>The Amazon Web Services account ID.</p>
    pub fn aws_account_id(mut self, input: impl Into<std::string::String>) -> Self {
        self.aws_account_id = Some(input.into());
        self
    }
    /// <p>The Amazon Web Services account ID.</p>
    pub fn set_aws_account_id(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.aws_account_id = input; self
    }
    /// <p>The ID of the data source. This ID is unique per Amazon Web Services Region for each Amazon Web Services account. </p>
    pub fn data_source_id(mut self, input: impl Into<std::string::String>) -> Self {
        self.data_source_id = Some(input.into());
        self
    }
    /// <p>The ID of the data source. This ID is unique per Amazon Web Services Region for each Amazon Web Services account. </p>
    pub fn set_data_source_id(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.data_source_id = input; self
    }
    /// <p>A display name for the data source.</p>
    pub fn name(mut self, input: impl Into<std::string::String>) -> Self {
        self.name = Some(input.into());
        self
    }
    /// <p>A display name for the data source.</p>
    pub fn set_name(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.name = input; self
    }
    /// <p>The parameters that Amazon QuickSight uses to connect to your underlying source.</p>
    pub fn data_source_parameters(mut self, input: crate::types::DataSourceParameters) -> Self {
        self.data_source_parameters = Some(input);
        self
    }
    /// <p>The parameters that Amazon QuickSight uses to connect to your underlying source.</p>
    pub fn set_data_source_parameters(mut self, input: std::option::Option<crate::types::DataSourceParameters>) -> Self {
        self.data_source_parameters = input; self
    }
    /// <p>The credentials that Amazon QuickSight that uses to connect to your underlying source. Currently, only credentials based on user name and password are supported.</p>
    pub fn credentials(mut self, input: crate::types::DataSourceCredentials) -> Self {
        self.credentials = Some(input);
        self
    }
    /// <p>The credentials that Amazon QuickSight that uses to connect to your underlying source. Currently, only credentials based on user name and password are supported.</p>
    pub fn set_credentials(mut self, input: std::option::Option<crate::types::DataSourceCredentials>) -> Self {
        self.credentials = input; self
    }
    /// <p>Use this parameter only when you want Amazon QuickSight to use a VPC connection when connecting to your underlying source.</p>
    pub fn vpc_connection_properties(mut self, input: crate::types::VpcConnectionProperties) -> Self {
        self.vpc_connection_properties = Some(input);
        self
    }
    /// <p>Use this parameter only when you want Amazon QuickSight to use a VPC connection when connecting to your underlying source.</p>
    pub fn set_vpc_connection_properties(mut self, input: std::option::Option<crate::types::VpcConnectionProperties>) -> Self {
        self.vpc_connection_properties = input; self
    }
    /// <p>Secure Socket Layer (SSL) properties that apply when Amazon QuickSight connects to your underlying source.</p>
    pub fn ssl_properties(mut self, input: crate::types::SslProperties) -> Self {
        self.ssl_properties = Some(input);
        self
    }
    /// <p>Secure Socket Layer (SSL) properties that apply when Amazon QuickSight connects to your underlying source.</p>
    pub fn set_ssl_properties(mut self, input: std::option::Option<crate::types::SslProperties>) -> Self {
        self.ssl_properties = input; self
    }
    /// Consumes the builder and constructs a [`UpdateDataSourceInput`](crate::operation::update_data_source::UpdateDataSourceInput).
    pub fn build(self) -> Result<crate::operation::update_data_source::UpdateDataSourceInput, aws_smithy_http::operation::error::BuildError> {
        Ok(
            crate::operation::update_data_source::UpdateDataSourceInput {
                aws_account_id: self.aws_account_id
                ,
                data_source_id: self.data_source_id
                ,
                name: self.name
                ,
                data_source_parameters: self.data_source_parameters
                ,
                credentials: self.credentials
                ,
                vpc_connection_properties: self.vpc_connection_properties
                ,
                ssl_properties: self.ssl_properties
                ,
            }
        )
    }
}
impl std::fmt::Debug for UpdateDataSourceInputBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("UpdateDataSourceInputBuilder");
        formatter.field("aws_account_id", &self.aws_account_id);
        formatter.field("data_source_id", &self.data_source_id);
        formatter.field("name", &self.name);
        formatter.field("data_source_parameters", &self.data_source_parameters);
        formatter.field("credentials", &"*** Sensitive Data Redacted ***");
        formatter.field("vpc_connection_properties", &self.vpc_connection_properties);
        formatter.field("ssl_properties", &self.ssl_properties);
        formatter.finish()
    }
}

