name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
env:
  rust_version: 1.51.0

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_version }}
      - name: install cargo audit
        run: cargo install cargo-audit
      - name: Run audit
        # chrono, a Rust date-time crate we use for timestamp parsing was added
        # to the RustSec vulnerability database because of a call to localtime_r.
        # We use chrono for an extremely narrow use case of converting epoch timestamps to UTC dates
        # (so we never invoke the problematic behavior that results from attempting to determine
        # the local time of the current platform).
        #
        # There currently is no release from chrono that rectifies the issue, and we are working
        # on a mitigation to ensure that we either use a patched version of chrono or add a deny-lint
        # to call any chrono methods other than the method we use currently.
        run: cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2020-0159
