on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Generate docs
        run: cargo +nightly doc --target-dir ../docs-new --no-deps
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
        working-directory: sdk
