#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script contains additional CI checks to run for this specific package

set -e

# TODO(msrvUpgrade): This can be enabled when upgrading to Rust 1.71
# echo '### Checking compilation under WASM'
# cargo hack check --no-dev-deps --target wasm32-unknown-unknown

echo "### Checking for duplicate dependency versions in the normal dependency graph with all features enabled"
cargo tree -d --edges normal --all-features

echo "### Testing every combination of features (excluding --all-features)"
cargo hack test --feature-powerset --exclude-all-features --exclude-features native-tls
