// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Represents the properties of the scaling policy.</p>
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct AutoScalingPolicyDescription  {
    /// <p>The name of the scaling policy.</p>
    #[doc(hidden)]
    pub policy_name: std::option::Option<std::string::String>,
    /// <p>Represents a target tracking scaling policy configuration.</p>
    #[doc(hidden)]
    pub target_tracking_scaling_policy_configuration: std::option::Option<crate::types::AutoScalingTargetTrackingScalingPolicyConfigurationDescription>,
}
impl AutoScalingPolicyDescription {
    /// <p>The name of the scaling policy.</p>
    pub fn policy_name(&self) -> std::option::Option<& str> {
        self.policy_name.as_deref()
    }
    /// <p>Represents a target tracking scaling policy configuration.</p>
    pub fn target_tracking_scaling_policy_configuration(&self) -> std::option::Option<& crate::types::AutoScalingTargetTrackingScalingPolicyConfigurationDescription> {
        self.target_tracking_scaling_policy_configuration.as_ref()
    }
}
impl AutoScalingPolicyDescription {
    /// Creates a new builder-style object to manufacture [`AutoScalingPolicyDescription`](crate::types::AutoScalingPolicyDescription).
    pub fn builder() -> crate::types::builders::AutoScalingPolicyDescriptionBuilder {
        crate::types::builders::AutoScalingPolicyDescriptionBuilder::default()
    }
}

/// A builder for [`AutoScalingPolicyDescription`](crate::types::AutoScalingPolicyDescription).
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::default::Default, std::fmt::Debug)]
pub struct AutoScalingPolicyDescriptionBuilder {
    pub(crate) policy_name: std::option::Option<std::string::String>,
    pub(crate) target_tracking_scaling_policy_configuration: std::option::Option<crate::types::AutoScalingTargetTrackingScalingPolicyConfigurationDescription>,
}
impl AutoScalingPolicyDescriptionBuilder {
    /// <p>The name of the scaling policy.</p>
    pub fn policy_name(mut self, input: impl Into<std::string::String>) -> Self {
        self.policy_name = Some(input.into());
        self
    }
    /// <p>The name of the scaling policy.</p>
    pub fn set_policy_name(mut self, input: std::option::Option<std::string::String>) -> Self {
        self.policy_name = input; self
    }
    /// <p>Represents a target tracking scaling policy configuration.</p>
    pub fn target_tracking_scaling_policy_configuration(mut self, input: crate::types::AutoScalingTargetTrackingScalingPolicyConfigurationDescription) -> Self {
        self.target_tracking_scaling_policy_configuration = Some(input);
        self
    }
    /// <p>Represents a target tracking scaling policy configuration.</p>
    pub fn set_target_tracking_scaling_policy_configuration(mut self, input: std::option::Option<crate::types::AutoScalingTargetTrackingScalingPolicyConfigurationDescription>) -> Self {
        self.target_tracking_scaling_policy_configuration = input; self
    }
    /// Consumes the builder and constructs a [`AutoScalingPolicyDescription`](crate::types::AutoScalingPolicyDescription).
    pub fn build(self) -> crate::types::AutoScalingPolicyDescription {
        crate::types::AutoScalingPolicyDescription {
            policy_name: self.policy_name
            ,
            target_tracking_scaling_policy_configuration: self.target_tracking_scaling_policy_configuration
            ,
        }
    }
}

