[package]
name = "smithy-async"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
edition = "2018"

[features]
rt-tokio = ["tokio"]
default = ["rt-tokio"]

[dependencies]
pin-project-lite = "0.2"
tokio = { version = "1.6", features = ["time"], optional = true }

[dev-dependencies]
tokio = { version = "1.6", features = ["rt", "macros"] }
futures-util = "0.3.16"
